# Generated by Django 5.0.2 on 2024-02-11 06:54

import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomateU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.BooleanField(default=False)),
                ('on', models.IntegerField()),
                ('man', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertise')),
                ('text', models.TextField(max_length=500)),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('exp_date', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2024, 3, 12, 10, 24, 42, 724171))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirectionU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=400)),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('he_she', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roomate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction', to='direct.roomateu')),
            ],
        ),
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='direct.roomateu')),
            ],
        ),
    ]
