# Generated by Django 5.0.2 on 2024-02-11 07:13

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='exp_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2024, 3, 12, 10, 43, 1, 604459)),
        ),
    ]
