# Generated by Django 5.0.2 on 2024-02-11 07:14

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0003_alter_advertise_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='exp_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2024, 3, 12, 10, 44, 9, 619066)),
        ),
    ]
