# Generated by Django 4.0.6 on 2022-09-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fathertopic',
            name='disliked',
        ),
        migrations.RemoveField(
            model_name='fathertopic',
            name='liked',
        ),
        migrations.AlterField(
            model_name='response',
            name='respon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='topic.topic'),
        ),
    ]
