# Generated by Django 4.0.6 on 2022-09-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_remove_fathertopic_disliked_remove_fathertopic_liked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='total_responses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
