# Generated by Django 4.0.6 on 2022-09-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_alter_topic_total_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fathertopic',
            name='total_resposes',
        ),
    ]
