# Generated by Django 4.0.6 on 2022-09-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0005_remove_fathertopic_total_resposes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='total_responses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
