# Generated by Django 4.0.6 on 2022-09-18 13:54

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0011_mostreact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostreact',
            name='day',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
