# Generated by Django 4.0.6 on 2022-09-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0012_alter_mostreact_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostreact',
            name='topic_total_responses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
