# Generated by Django 4.0.6 on 2022-09-19 16:10

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0015_alter_rewarded_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewarded',
            name='day',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
