# Generated by Django 5.0.2 on 2024-02-11 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('topic', '0020_alter_sametopics_relateds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fathertopic',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike_users', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='fathertopic',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='fathertopic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='rewarded',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user'),
        ),
    ]
